### ISSUE TITLE
Searching seems not to work in FF Nightly

### ISSUE THREAD

**Issue by scheinercc** [mozilla/platform-status#511] opened 2018-01-05 00:28 UTC
Landing on https://platform-status.mozilla.org/ "Search features" is not doing anything for me atm.
I get this error in the console, not sure if it is related:
![image](https://user-images.githubusercontent.com/817856/34590531-7f5922fa-f20b-11e7-8877-7c4bfd566bd1.png)

**Comment by marco-c** [comment] 2018-01-05 09:55
Duplicate of #509.

**Closed by marco-c** 2018-01-05 09:55 UTC
Labels: duplicate
